<a href="https://colab.research.google.com/github/ALAIKBITTUQOH/Alaik-Bittuqoh-/blob/main/23422033_Alaik_Bittuqoh_tugas_citra_digital.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# Variabel H untuk kernel atau filter
H = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

# Variabel X untuk image input/image original (contoh matriks 5x5)
X = np.array([
    [10, 20, 30, 40, 50],
    [60, 70, 80, 90, 100],
    [110, 120, 130, 140, 150],
    [160, 170, 180, 190, 200],
    [210, 220, 230, 240, 250]
])

# Ukuran filter
nFilterX, nFilterY = H.shape

# Membuat matriks Y (output) dengan ukuran yang sesuai
output_height = X.shape[0] - nFilterX + 1
output_width = X.shape[1] - nFilterY + 1
Y = np.zeros((output_height, output_width))

# Proses filtering
for x in range(output_width):
    for y in range(output_height):
        z = 0
        for k1 in range(nFilterX):
            for k2 in range(nFilterY):
                z += H[k1, k2] * X[y + k1, x + k2]
        Y[y, x] = z

# Menampilkan hasil
print("Input Image (X):\n", X)
print("Filter (H):\n", H)
print("Output Image (Y):\n", Y)

Input Image (X):
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]
 [210 220 230 240 250]]
Filter (H):
 [[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]
Output Image (Y):
 [[-60. -60. -60.]
 [-60. -60. -60.]
 [-60. -60. -60.]]
