<a href="https://colab.research.google.com/github/ALAIKBITTUQOH/Alaik-Bittuqoh-/blob/main/Tugas_Pengolahan_Citra_Digital.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Variabel H untuk kernel atau filter
H = np.array([
    [1, 1, 1],
    [1, 4, 1],
    [1, 1, 1]
])

# Variabel X untuk image input/image original (contoh matriks 5x5)
X = np.array([
    [0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0],
    [0, 1, 1, 1, 0, 0],
    [0, 1, 1, 1, 0, 0],
    [0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0]
])

# Ukuran filter
nFilterX, nFilterY = H.shape

# Membuat matriks Y (output) dengan ukuran yang sesuai
output_height = X.shape[0] - nFilterX + 1
output_width = X.shape[1] - nFilterY + 1
Y = np.zeros((output_height, output_width))

# Proses filtering
for x in range(output_width):
    for y in range(output_height):
        z = 0
        for k1 in range(nFilterX):
            for k2 in range(nFilterY):
                z += H[k1, k2] * X[y + k1, x + k2]
        Y[y, x] = z

# Menampilkan hasil
print("Input Image (X):\n", X)
print("Filter (H):\n", H)
print("Output Image (Y):\n", Y)

Input Image (X):
 [[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 1 1 0 0]
 [0 1 1 1 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 0]]
Filter (H):
 [[1 1 1]
 [1 4 1]
 [1 1 1]]
Output Image (Y):
 [[ 6.  4.  2.  1.]
 [ 8. 10.  7.  2.]
 [ 8. 10.  7.  2.]
 [ 6.  4.  2.  1.]]
